create table if not exists public.billing_orders (
  order_id text primary key,
  user_id text not null,
  plan_tier text not null,
  order_kind text not null default 'subscription',
  credit_pack_units integer not null default 0,
  amount integer not null,
  currency text not null default 'KRW',
  status text not null default 'READY',
  order_name text not null,
  payment_key text,
  fail_code text,
  fail_message text,
  toss_response jsonb,
  approved_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.billing_orders
  add column if not exists order_kind text not null default 'subscription',
  add column if not exists credit_pack_units integer not null default 0,
  add column if not exists updated_at timestamptz default now();

update public.billing_orders
set
  order_kind = case
    when coalesce(order_kind, '') = '' then 'subscription'
    else order_kind
  end,
  credit_pack_units = greatest(0, coalesce(credit_pack_units, 0)),
  updated_at = coalesce(updated_at, now())
where coalesce(order_kind, '') = ''
   or credit_pack_units is null
   or credit_pack_units < 0
   or updated_at is null;

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'billing_orders_order_kind_check'
      and conrelid = 'public.billing_orders'::regclass
  ) then
    alter table public.billing_orders drop constraint billing_orders_order_kind_check;
  end if;
end;
$$;

alter table public.billing_orders
  add constraint billing_orders_order_kind_check
  check (order_kind in ('subscription', 'credit_pack'));

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'billing_orders_credit_pack_units_nonnegative'
      and conrelid = 'public.billing_orders'::regclass
  ) then
    alter table public.billing_orders drop constraint billing_orders_credit_pack_units_nonnegative;
  end if;
end;
$$;

alter table public.billing_orders
  add constraint billing_orders_credit_pack_units_nonnegative
  check (credit_pack_units >= 0);

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'billing_orders_credit_pack_units_consistency_check'
      and conrelid = 'public.billing_orders'::regclass
  ) then
    alter table public.billing_orders drop constraint billing_orders_credit_pack_units_consistency_check;
  end if;
end;
$$;

alter table public.billing_orders
  add constraint billing_orders_credit_pack_units_consistency_check
  check (
    (order_kind = 'subscription' and credit_pack_units = 0)
    or
    (order_kind = 'credit_pack' and credit_pack_units > 0)
  );

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'billing_orders_status_check'
      and conrelid = 'public.billing_orders'::regclass
  ) then
    alter table public.billing_orders drop constraint billing_orders_status_check;
  end if;
end;
$$;

alter table public.billing_orders
  add constraint billing_orders_status_check
  check (status in ('READY', 'DONE', 'FAILED', 'CANCELED'));

create index if not exists idx_billing_orders_user_id_created_at
  on public.billing_orders (user_id, created_at desc);

create index if not exists idx_billing_orders_user_order_kind_created
  on public.billing_orders (user_id, order_kind, created_at desc);

create index if not exists idx_billing_orders_status
  on public.billing_orders (status);

create table if not exists public.billing_refund_requests (
  id bigint generated by default as identity primary key,
  user_id text not null,
  order_id text not null,
  reason text not null,
  status text not null default 'REQUESTED',
  admin_note text,
  reviewed_by text,
  reviewed_at timestamptz,
  review_note text,
  executed_by text,
  executed_at timestamptz,
  cancel_amount integer,
  currency text not null default 'KRW',
  toss_payment_key_snapshot text,
  toss_cancel_transaction_key text,
  gateway_response jsonb,
  error_code text,
  error_message text,
  retry_count integer not null default 0,
  next_retry_at timestamptz,
  requested_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  notified_at timestamptz,
  notify_user_sent_at timestamptz
);

create table if not exists public.billing_refund_events (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.billing_refund_requests(id) on delete cascade,
  user_id text not null,
  order_id text not null,
  actor_user_id text,
  actor_role text not null default 'system',
  event_type text not null,
  from_status text,
  to_status text,
  message text,
  metadata jsonb,
  created_at timestamptz not null default now()
);

-- cleanup: 중도 취소/실패 주문은 이력에서 제거 (완료 결제/완료 환불 이력만 유지)
delete from public.billing_orders
where status in ('READY', 'FAILED');

delete from public.billing_orders
where status = 'CANCELED'
  and payment_key is null;

-- cleanup: 사용자 철회 환불 요청은 이력에서 제거
delete from public.billing_refund_requests
where status = 'WITHDRAWN';

select pg_notify('pgrst', 'reload schema');
