alter table public.rnest_users
  add column if not exists med_safety_standard_included_credits integer not null default 0,
  add column if not exists med_safety_standard_extra_credits integer not null default 0,
  add column if not exists med_safety_premium_included_credits integer not null default 0,
  add column if not exists med_safety_premium_extra_credits integer not null default 0;

update public.rnest_users
set med_safety_standard_extra_credits = greatest(coalesce(med_safety_standard_extra_credits, 0), coalesce(med_safety_extra_credits, 0))
where coalesce(med_safety_extra_credits, 0) > 0;

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'rnest_users_subscription_tier_check'
      and conrelid = 'public.rnest_users'::regclass
  ) then
    alter table public.rnest_users drop constraint rnest_users_subscription_tier_check;
  end if;
end $$;

alter table public.rnest_users
  add constraint rnest_users_subscription_tier_check
  check (subscription_tier in ('free', 'plus', 'pro'));

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'rnest_users_med_safety_standard_included_nonnegative'
      and conrelid = 'public.rnest_users'::regclass
  ) then
    alter table public.rnest_users drop constraint rnest_users_med_safety_standard_included_nonnegative;
  end if;
  if exists (
    select 1
    from pg_constraint
    where conname = 'rnest_users_med_safety_standard_extra_nonnegative'
      and conrelid = 'public.rnest_users'::regclass
  ) then
    alter table public.rnest_users drop constraint rnest_users_med_safety_standard_extra_nonnegative;
  end if;
  if exists (
    select 1
    from pg_constraint
    where conname = 'rnest_users_med_safety_premium_included_nonnegative'
      and conrelid = 'public.rnest_users'::regclass
  ) then
    alter table public.rnest_users drop constraint rnest_users_med_safety_premium_included_nonnegative;
  end if;
  if exists (
    select 1
    from pg_constraint
    where conname = 'rnest_users_med_safety_premium_extra_nonnegative'
      and conrelid = 'public.rnest_users'::regclass
  ) then
    alter table public.rnest_users drop constraint rnest_users_med_safety_premium_extra_nonnegative;
  end if;
end $$;

alter table public.rnest_users
  add constraint rnest_users_med_safety_standard_included_nonnegative check (med_safety_standard_included_credits >= 0),
  add constraint rnest_users_med_safety_standard_extra_nonnegative check (med_safety_standard_extra_credits >= 0),
  add constraint rnest_users_med_safety_premium_included_nonnegative check (med_safety_premium_included_credits >= 0),
  add constraint rnest_users_med_safety_premium_extra_nonnegative check (med_safety_premium_extra_credits >= 0);

alter table public.billing_orders
  add column if not exists product_id text,
  add column if not exists credit_type text;

update public.billing_orders
set product_id = case
    when product_id is not null then product_id
    when order_kind = 'subscription' and lower(order_id) like '%plus%' then 'plus'
    when order_kind = 'subscription' and lower(order_id) like '%pro%' then 'pro'
    when lower(order_id) like '%premium30%' then 'premium30'
    when lower(order_id) like '%premium10%' then 'premium10'
    when lower(order_id) like '%standard30%' then 'standard30'
    when lower(order_id) like '%standard10%' then 'standard10'
    when lower(order_id) like '%credit30%' then 'standard30'
    when lower(order_id) like '%credit10%' then 'standard10'
    else product_id
  end,
  credit_type = case
    when credit_type is not null then credit_type
    when lower(coalesce(product_id, '')) like 'premium%' then 'premium'
    when lower(coalesce(product_id, '')) like 'standard%' then 'standard'
    when lower(order_name) like '%프리미엄%' or lower(order_name) like '%premium%' then 'premium'
    when order_kind = 'credit_pack' then 'standard'
    else credit_type
  end;

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'billing_orders_plan_tier_check'
      and conrelid = 'public.billing_orders'::regclass
  ) then
    alter table public.billing_orders drop constraint billing_orders_plan_tier_check;
  end if;
end $$;

alter table public.billing_orders
  add constraint billing_orders_plan_tier_check
  check (plan_tier in ('free', 'plus', 'pro'));

create index if not exists idx_billing_orders_product_id_created
  on public.billing_orders (product_id, created_at desc);

create table if not exists public.billing_analytics_events (
  id bigint generated by default as identity primary key,
  user_id text not null references public.rnest_users(user_id) on delete cascade,
  event_name text not null,
  plan_tier_snapshot text,
  props jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_billing_analytics_events_created
  on public.billing_analytics_events (created_at desc);

create index if not exists idx_billing_analytics_events_name_created
  on public.billing_analytics_events (event_name, created_at desc);

alter table public.billing_analytics_events enable row level security;

drop policy if exists "billing_analytics_events_select_own" on public.billing_analytics_events;
create policy "billing_analytics_events_select_own"
  on public.billing_analytics_events for select to authenticated
  using (((select auth.uid())::text = user_id));

grant select on table public.billing_analytics_events to authenticated;
