begin;

alter table public.rnest_users
  add column if not exists onboarding_completed_at timestamptz;

create table if not exists public.user_service_consents (
  user_id text primary key references public.rnest_users(user_id) on delete cascade,
  records_storage_consented_at timestamptz not null,
  ai_usage_consented_at timestamptz not null,
  consent_completed_at timestamptz not null,
  consent_version text not null,
  privacy_version text not null,
  terms_version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_service_consent_events (
  id bigint generated by default as identity primary key,
  user_id text not null references public.rnest_users(user_id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint user_service_consent_events_payload_object_check
    check (jsonb_typeof(payload) = 'object')
);

drop trigger if exists trg_set_updated_at_user_service_consents on public.user_service_consents;
create trigger trg_set_updated_at_user_service_consents
before update on public.user_service_consents
for each row execute function public.tg_set_updated_at();

create index if not exists idx_user_service_consents_completed
  on public.user_service_consents (consent_completed_at desc);

create index if not exists idx_user_service_consent_events_user_created
  on public.user_service_consent_events (user_id, created_at desc);

alter table public.user_service_consents enable row level security;
alter table public.user_service_consent_events enable row level security;

drop policy if exists "user_service_consents_select_own" on public.user_service_consents;
drop policy if exists "user_service_consents_insert_own" on public.user_service_consents;
drop policy if exists "user_service_consents_update_own" on public.user_service_consents;
drop policy if exists "user_service_consent_events_select_own" on public.user_service_consent_events;
drop policy if exists "user_service_consent_events_insert_own" on public.user_service_consent_events;

create policy "user_service_consents_select_own"
  on public.user_service_consents
  for select
  to authenticated
  using ((select auth.uid())::text = user_id);

create policy "user_service_consents_insert_own"
  on public.user_service_consents
  for insert
  to authenticated
  with check ((select auth.uid())::text = user_id);

create policy "user_service_consents_update_own"
  on public.user_service_consents
  for update
  to authenticated
  using ((select auth.uid())::text = user_id)
  with check ((select auth.uid())::text = user_id);

create policy "user_service_consent_events_select_own"
  on public.user_service_consent_events
  for select
  to authenticated
  using ((select auth.uid())::text = user_id);

create policy "user_service_consent_events_insert_own"
  on public.user_service_consent_events
  for insert
  to authenticated
  with check ((select auth.uid())::text = user_id);

grant select, insert, update on table public.user_service_consents to authenticated;
grant select, insert on table public.user_service_consent_events to authenticated;
grant usage, select on sequence public.user_service_consent_events_id_seq to authenticated;

commit;
