ALTER TABLE public.shop_products
  ADD COLUMN IF NOT EXISTS image_urls text[] NOT NULL DEFAULT '{}'::text[];

ALTER TABLE public.shop_products
  ADD COLUMN IF NOT EXISTS specs jsonb NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE public.shop_orders
  ADD COLUMN IF NOT EXISTS shipping_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS public.shop_customer_profiles (
  user_id uuid PRIMARY KEY,
  recipient_name text NOT NULL DEFAULT '',
  phone text NOT NULL DEFAULT '',
  postal_code text NOT NULL DEFAULT '',
  address_line1 text NOT NULL DEFAULT '',
  address_line2 text NOT NULL DEFAULT '',
  delivery_note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.shop_reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id text NOT NULL,
  user_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
  title text NOT NULL DEFAULT '',
  body text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  UNIQUE (product_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_shop_reviews_product_updated
  ON public.shop_reviews (product_id, updated_at DESC);

ALTER TABLE public.shop_customer_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shop_reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS shop_customer_profiles_owner_read ON public.shop_customer_profiles;
CREATE POLICY shop_customer_profiles_owner_read
  ON public.shop_customer_profiles
  FOR SELECT
  USING (auth.uid() IS NOT NULL AND auth.uid() = user_id);

DROP POLICY IF EXISTS shop_customer_profiles_owner_upsert ON public.shop_customer_profiles;
CREATE POLICY shop_customer_profiles_owner_upsert
  ON public.shop_customer_profiles
  FOR ALL
  USING (auth.uid() IS NOT NULL AND auth.uid() = user_id)
  WITH CHECK (auth.uid() IS NOT NULL AND auth.uid() = user_id);

DROP POLICY IF EXISTS shop_reviews_public_read ON public.shop_reviews;
CREATE POLICY shop_reviews_public_read
  ON public.shop_reviews
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS shop_reviews_owner_upsert ON public.shop_reviews;
CREATE POLICY shop_reviews_owner_upsert
  ON public.shop_reviews
  FOR ALL
  USING (auth.uid() IS NOT NULL AND auth.uid() = user_id)
  WITH CHECK (auth.uid() IS NOT NULL AND auth.uid() = user_id);

DROP TRIGGER IF EXISTS trg_set_updated_at_shop_customer_profiles ON public.shop_customer_profiles;
CREATE TRIGGER trg_set_updated_at_shop_customer_profiles
  BEFORE UPDATE ON public.shop_customer_profiles
  FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();

DROP TRIGGER IF EXISTS trg_set_updated_at_shop_reviews ON public.shop_reviews;
CREATE TRIGGER trg_set_updated_at_shop_reviews
  BEFORE UPDATE ON public.shop_reviews
  FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();
