CREATE TABLE IF NOT EXISTS public.shop_claims (
  claim_id text PRIMARY KEY,
  order_id text NOT NULL REFERENCES public.shop_orders(order_id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  claim_type text NOT NULL CHECK (claim_type IN ('refund', 'exchange')),
  status text NOT NULL DEFAULT 'requested'
    CHECK (status IN ('requested', 'approved', 'rejected', 'return_shipped', 'return_received', 'refund_completed', 'exchange_shipped', 'withdrawn')),
  reason text NOT NULL DEFAULT '',
  detail text NOT NULL DEFAULT '',
  admin_note text NULL,
  requested_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  reviewed_at timestamptz NULL,
  reviewed_by uuid NULL,
  return_tracking_number text NULL,
  return_courier text NULL,
  return_shipped_at timestamptz NULL,
  return_received_at timestamptz NULL,
  exchange_tracking_number text NULL,
  exchange_courier text NULL,
  exchange_shipped_at timestamptz NULL,
  refund_completed_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.shop_claim_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_id text NOT NULL REFERENCES public.shop_claims(claim_id) ON DELETE CASCADE,
  order_id text NOT NULL REFERENCES public.shop_orders(order_id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  actor_user_id uuid NULL,
  actor_role text NOT NULL DEFAULT 'system' CHECK (actor_role IN ('system', 'user', 'admin')),
  event_type text NOT NULL,
  status text NOT NULL,
  message text NULL,
  metadata jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.shop_claim_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_id text NOT NULL REFERENCES public.shop_claims(claim_id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  file_url text NOT NULL,
  file_kind text NOT NULL DEFAULT 'image',
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS idx_shop_claims_user_updated
  ON public.shop_claims (user_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_shop_claims_order_updated
  ON public.shop_claims (order_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_shop_claims_status_updated
  ON public.shop_claims (status, updated_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_shop_claims_order_active
  ON public.shop_claims (order_id)
  WHERE status IN ('requested', 'approved', 'return_shipped', 'return_received');

CREATE INDEX IF NOT EXISTS idx_shop_claim_events_claim_created
  ON public.shop_claim_events (claim_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_shop_claim_attachments_claim_created
  ON public.shop_claim_attachments (claim_id, created_at DESC);

ALTER TABLE public.shop_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shop_claim_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shop_claim_attachments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS shop_claims_owner_read ON public.shop_claims;
CREATE POLICY shop_claims_owner_read
  ON public.shop_claims
  FOR SELECT
  USING (auth.uid() IS NOT NULL AND auth.uid() = user_id);

DROP POLICY IF EXISTS shop_claim_events_owner_read ON public.shop_claim_events;
CREATE POLICY shop_claim_events_owner_read
  ON public.shop_claim_events
  FOR SELECT
  USING (auth.uid() IS NOT NULL AND auth.uid() = user_id);

DROP POLICY IF EXISTS shop_claim_attachments_owner_read ON public.shop_claim_attachments;
CREATE POLICY shop_claim_attachments_owner_read
  ON public.shop_claim_attachments
  FOR SELECT
  USING (auth.uid() IS NOT NULL AND auth.uid() = user_id);

DROP TRIGGER IF EXISTS trg_set_updated_at_shop_claims ON public.shop_claims;
CREATE TRIGGER trg_set_updated_at_shop_claims
  BEFORE UPDATE ON public.shop_claims
  FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();
