CREATE TABLE IF NOT EXISTS public.shop_products (
  id text PRIMARY KEY,
  name text NOT NULL,
  subtitle text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  category text NOT NULL,
  visual_label text NOT NULL,
  visual_class text NOT NULL,
  price_label text NOT NULL DEFAULT '',
  partner_label text NOT NULL DEFAULT '',
  partner_status text NOT NULL DEFAULT '',
  external_url text NULL,
  price_krw integer NULL,
  checkout_enabled boolean NOT NULL DEFAULT false,
  benefit_tags text[] NOT NULL DEFAULT '{}'::text[],
  use_moments text[] NOT NULL DEFAULT '{}'::text[],
  caution text NOT NULL DEFAULT '',
  priority integer NOT NULL DEFAULT 0,
  match_signals text[] NOT NULL DEFAULT '{}'::text[],
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.shop_orders (
  order_id text PRIMARY KEY,
  user_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'READY',
  product_id text NOT NULL,
  product_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  amount integer NOT NULL,
  currency text NOT NULL DEFAULT 'KRW',
  payment_key text NULL,
  payment_summary jsonb NULL,
  approved_at timestamptz NULL,
  fail_code text NULL,
  fail_message text NULL,
  refund_status text NOT NULL DEFAULT 'none',
  refund_reason text NULL,
  refund_requested_at timestamptz NULL,
  refund_reviewed_at timestamptz NULL,
  refund_reviewed_by uuid NULL,
  refund_note text NULL,
  refund_cancel_amount integer NULL,
  refund_canceled_at timestamptz NULL,
  refund_summary jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.shop_order_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id text NOT NULL REFERENCES public.shop_orders(order_id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  actor_user_id uuid NULL,
  actor_role text NOT NULL DEFAULT 'system',
  event_type text NOT NULL,
  status text NOT NULL,
  message text NULL,
  metadata jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS idx_shop_products_active_priority
  ON public.shop_products (active, priority DESC, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_shop_orders_user_updated
  ON public.shop_orders (user_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_shop_orders_status_updated
  ON public.shop_orders (status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_shop_order_events_order_created
  ON public.shop_order_events (order_id, created_at DESC);

ALTER TABLE public.shop_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shop_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shop_order_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS shop_products_public_read ON public.shop_products;
CREATE POLICY shop_products_public_read
  ON public.shop_products
  FOR SELECT
  USING (active = true);

DROP POLICY IF EXISTS shop_orders_owner_read ON public.shop_orders;
CREATE POLICY shop_orders_owner_read
  ON public.shop_orders
  FOR SELECT
  USING (auth.uid() IS NOT NULL AND auth.uid() = user_id);

DROP POLICY IF EXISTS shop_order_events_owner_read ON public.shop_order_events;
CREATE POLICY shop_order_events_owner_read
  ON public.shop_order_events
  FOR SELECT
  USING (auth.uid() IS NOT NULL AND auth.uid() = user_id);

DROP TRIGGER IF EXISTS trg_set_updated_at_shop_products ON public.shop_products;
CREATE TRIGGER trg_set_updated_at_shop_products
  BEFORE UPDATE ON public.shop_products
  FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();

DROP TRIGGER IF EXISTS trg_set_updated_at_shop_orders ON public.shop_orders;
CREATE TRIGGER trg_set_updated_at_shop_orders
  BEFORE UPDATE ON public.shop_orders
  FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();

-- Schema-only setup:
-- This migration intentionally does not copy, update, or backfill any existing data.
-- Existing ai_content or legacy shop records remain untouched.
